// <auto-generated />
namespace Sem3FinalProjectTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixingall : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixingall));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121449125_Fixing-all"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
